#ifndef CONFIG_H
#define CONFIG_H

#define BUFFER_SIZE 16
#define PAGE_SIZE 256
#define OFFSET_BITS 8
#define OFFSET_MASK 255

#define LOGICAL_ADDRESS_SPACE 65536
#define PHYSICAL_ADDRESS_SPACE 32768

#define PAGES (LOGICAL_ADDRESS_SPACE / PAGE_SIZE)
#define FRAMES (PHYSICAL_ADDRESS_SPACE / PAGE_SIZE)
#define TLB_SIZE 16

#endif
